[2024-09-01T11:27:26.115+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-01T11:27:26.775+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.branch_task_dd manual__2024-09-01T11:14:05.440921+00:00 [queued]>
[2024-09-01T11:27:26.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.branch_task_dd manual__2024-09-01T11:14:05.440921+00:00 [queued]>
[2024-09-01T11:27:26.808+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-01T11:27:26.853+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_task_dd> on 2024-09-01 11:14:05.440921+00:00
[2024-09-01T11:27:26.872+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=6903) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T11:27:26.877+0000] {standard_task_runner.py:64} INFO - Started process 6905 to run task
[2024-09-01T11:27:26.876+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'branch_task_dd', 'manual__2024-09-01T11:14:05.440921+00:00', '--job-id', '398', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp04u897yi']
[2024-09-01T11:27:26.884+0000] {standard_task_runner.py:91} INFO - Job 398: Subtask branch_task_dd
[2024-09-01T11:27:27.112+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.branch_task_dd manual__2024-09-01T11:14:05.440921+00:00 [running]> on host 19bb8daff211
[2024-09-01T11:27:27.447+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='branch_task_dd' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T11:14:05.440921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T11:14:05.440921+00:00'
[2024-09-01T11:27:27.451+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-01T11:27:27.482+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-09-01T11:27:27.508+0000] {python.py:237} INFO - Done. Returned value was: send_failure_email
[2024-09-01T11:27:27.510+0000] {branch.py:36} INFO - Branch into send_failure_email
[2024-09-01T11:27:27.511+0000] {skipmixin.py:178} INFO - Following branch send_failure_email
[2024-09-01T11:27:27.544+0000] {skipmixin.py:246} INFO - Skipping tasks [('send_email', -1)]
[2024-09-01T11:27:27.596+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-01T11:27:27.640+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=branch_task_dd, run_id=manual__2024-09-01T11:14:05.440921+00:00, execution_date=20240901T111405, start_date=20240901T112726, end_date=20240901T112727
[2024-09-01T11:27:27.699+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-01T11:27:27.774+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-01T11:27:27.778+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
