[2024-09-01T11:02:57.090+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-01T11:02:57.355+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.processing_data manual__2024-09-01T11:02:44.401588+00:00 [queued]>
[2024-09-01T11:02:57.373+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.processing_data manual__2024-09-01T11:02:44.401588+00:00 [queued]>
[2024-09-01T11:02:57.376+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-01T11:02:57.404+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): processing_data> on 2024-09-01 11:02:44.401588+00:00
[2024-09-01T11:02:57.413+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=6564) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T11:02:57.416+0000] {standard_task_runner.py:64} INFO - Started process 6566 to run task
[2024-09-01T11:02:57.417+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'processing_data', 'manual__2024-09-01T11:02:44.401588+00:00', '--job-id', '386', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp23k2bf4s']
[2024-09-01T11:02:57.422+0000] {standard_task_runner.py:91} INFO - Job 386: Subtask processing_data
[2024-09-01T11:02:57.493+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.processing_data manual__2024-09-01T11:02:44.401588+00:00 [running]> on host 19bb8daff211
[2024-09-01T11:02:57.686+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='jorgepons90@gmail.com,facturasjorgepons@gmail.com' AIRFLOW_CTX_DAG_OWNER='Jorge Pons' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='processing_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T11:02:44.401588+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T11:02:44.401588+00:00'
[2024-09-01T11:02:57.689+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-01T11:02:57.719+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-01T11:02:57.720+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/c_process_data.py", line 19, in process_data
    ti = kwargs['ti']
         ~~~~~~^^^^^^
KeyError: 'ti'
[2024-09-01T11:02:57.747+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_dag, task_id=processing_data, run_id=manual__2024-09-01T11:02:44.401588+00:00, execution_date=20240901T110244, start_date=20240901T110257, end_date=20240901T110257
[2024-09-01T11:02:57.786+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 386 for task processing_data ('ti'; 6566)
[2024-09-01T11:02:57.835+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-01T11:02:57.890+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-01T11:02:57.893+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
