[2024-08-16T00:15:39.529+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-16T00:15:41.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.send_email scheduled__2024-08-15T00:00:00+00:00 [queued]>
[2024-08-16T00:15:41.985+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.send_email scheduled__2024-08-15T00:00:00+00:00 [queued]>
[2024-08-16T00:15:41.987+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-16T00:15:42.028+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_email> on 2024-08-15 00:00:00+00:00
[2024-08-16T00:15:42.054+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1087) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-16T00:15:42.057+0000] {standard_task_runner.py:64} INFO - Started process 1089 to run task
[2024-08-16T00:15:42.057+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'send_email', 'scheduled__2024-08-15T00:00:00+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/envioemail.py', '--cfg-path', '/tmp/tmp4ur_hpne']
[2024-08-16T00:15:42.062+0000] {standard_task_runner.py:91} INFO - Job 232: Subtask send_email
[2024-08-16T00:15:42.163+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.send_email scheduled__2024-08-15T00:00:00+00:00 [running]> on host 36be84c641dc
[2024-08-16T00:15:42.402+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-08-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-15T00:00:00+00:00'
[2024-08-16T00:15:42.405+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-16T00:15:42.533+0000] {base.py:84} INFO - Using connection ID 'smtp_default' for task execution.
[2024-08-16T00:15:42.535+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-08-16T00:15:42.720+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-16T00:15:42.722+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 329, in _get_smtp_connection
    return smtplib.SMTP_SSL(host=host, port=port, timeout=timeout, context=ssl_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 1022, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 1028, in _get_socket
    new_socket = super()._get_socket(host, port, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 829, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 964, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
[2024-08-16T00:15:42.747+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_dag, task_id=send_email, run_id=scheduled__2024-08-15T00:00:00+00:00, execution_date=20240815T000000, start_date=20240816T001541, end_date=20240816T001542
[2024-08-16T00:15:42.779+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 232 for task send_email ([Errno -2] Name or service not known; 1089)
[2024-08-16T00:15:42.837+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-16T00:15:42.872+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16T00:15:42.876+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
