[2024-09-01T10:49:04.617+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-01T10:49:04.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.branch_task manual__2024-09-01T10:48:58.073286+00:00 [queued]>
[2024-09-01T10:49:05.018+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.branch_task manual__2024-09-01T10:48:58.073286+00:00 [queued]>
[2024-09-01T10:49:05.022+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-01T10:49:05.073+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-09-01 10:48:58.073286+00:00
[2024-09-01T10:49:05.091+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=6373) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T10:49:05.095+0000] {standard_task_runner.py:64} INFO - Started process 6375 to run task
[2024-09-01T10:49:05.094+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'branch_task', 'manual__2024-09-01T10:48:58.073286+00:00', '--job-id', '381', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpv0_9c10q']
[2024-09-01T10:49:05.098+0000] {standard_task_runner.py:91} INFO - Job 381: Subtask branch_task
[2024-09-01T10:49:05.197+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.branch_task manual__2024-09-01T10:48:58.073286+00:00 [running]> on host 19bb8daff211
[2024-09-01T10:49:05.393+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T10:48:58.073286+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T10:48:58.073286+00:00'
[2024-09-01T10:49:05.396+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-01T10:49:05.433+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-09-01T10:49:05.458+0000] {python.py:237} INFO - Done. Returned value was: send_failure_email
[2024-09-01T10:49:05.459+0000] {branch.py:36} INFO - Branch into send_failure_email
[2024-09-01T10:49:05.461+0000] {skipmixin.py:178} INFO - Following branch send_failure_email
[2024-09-01T10:49:05.501+0000] {skipmixin.py:246} INFO - Skipping tasks [('processing_data', -1)]
[2024-09-01T10:49:05.554+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-01T10:49:05.592+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=branch_task, run_id=manual__2024-09-01T10:48:58.073286+00:00, execution_date=20240901T104858, start_date=20240901T104904, end_date=20240901T104905
[2024-09-01T10:49:05.633+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-01T10:49:05.694+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-01T10:49:05.702+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
