[2024-08-15T10:05:47.867+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-15T10:05:48.261+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.send_email manual__2024-08-15T10:05:45.032626+00:00 [queued]>
[2024-08-15T10:05:48.290+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.send_email manual__2024-08-15T10:05:45.032626+00:00 [queued]>
[2024-08-15T10:05:48.295+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-15T10:05:48.338+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_email> on 2024-08-15 10:05:45.032626+00:00
[2024-08-15T10:05:48.356+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=910) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-15T10:05:48.362+0000] {standard_task_runner.py:64} INFO - Started process 912 to run task
[2024-08-15T10:05:48.361+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'send_email', 'manual__2024-08-15T10:05:45.032626+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/envioemail.py', '--cfg-path', '/tmp/tmpl_yhxf6b']
[2024-08-15T10:05:48.367+0000] {standard_task_runner.py:91} INFO - Job 223: Subtask send_email
[2024-08-15T10:05:48.487+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.send_email manual__2024-08-15T10:05:45.032626+00:00 [running]> on host f409994b1613
[2024-08-15T10:05:48.802+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-08-15T10:05:45.032626+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-15T10:05:45.032626+00:00'
[2024-08-15T10:05:48.806+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-15T10:05:48.892+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-08-15T10:05:48.897+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-08-15T10:05:48.898+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-08-15T10:05:48.901+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-15T10:05:48.905+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-08-15T10:05:48.937+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_dag, task_id=send_email, run_id=manual__2024-08-15T10:05:45.032626+00:00, execution_date=20240815T100545, start_date=20240815T100548, end_date=20240815T100548
[2024-08-15T10:05:48.978+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 223 for task send_email ([Errno 111] Connection refused; 912)
[2024-08-15T10:05:49.022+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-15T10:05:49.064+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-15T10:05:49.069+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
