[2024-08-31T17:55:38.691+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T17:55:39.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.execution_time manual__2024-08-31T16:50:00.890695+00:00 [queued]>
[2024-08-31T17:55:39.042+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.execution_time manual__2024-08-31T16:50:00.890695+00:00 [queued]>
[2024-08-31T17:55:39.046+0000] {taskinstance.py:2306} INFO - Starting attempt 25 of 26
[2024-08-31T17:55:39.077+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): execution_time> on 2024-08-31 16:50:00.890695+00:00
[2024-08-31T17:55:39.088+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3355) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T17:55:39.092+0000] {standard_task_runner.py:64} INFO - Started process 3357 to run task
[2024-08-31T17:55:39.092+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'execution_time', 'manual__2024-08-31T16:50:00.890695+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/envioemail.py', '--cfg-path', '/tmp/tmp91eqkee3']
[2024-08-31T17:55:39.097+0000] {standard_task_runner.py:91} INFO - Job 355: Subtask execution_time
[2024-08-31T17:55:39.185+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.execution_time manual__2024-08-31T16:50:00.890695+00:00 [running]> on host 19bb8daff211
[2024-08-31T17:55:39.367+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='jorgepons90@gmail.com,facturasjorgepons@gmail.com' AIRFLOW_CTX_DAG_OWNER='Jorge Pons' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='execution_time' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T16:50:00.890695+00:00' AIRFLOW_CTX_TRY_NUMBER='25' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T16:50:00.890695+00:00'
[2024-08-31T17:55:39.369+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T17:55:39.425+0000] {logging_mixin.py:188} INFO - <class 'float'>
[2024-08-31T17:55:39.426+0000] {logging_mixin.py:188} INFO - 0.400908
[2024-08-31T17:55:39.465+0000] {base.py:84} INFO - Using connection ID 'my_mssql_conn_id' for task execution.
[2024-08-31T17:55:39.608+0000] {logging_mixin.py:188} INFO - 1
[2024-08-31T17:55:39.653+0000] {logging_mixin.py:188} INFO - Error: (208, b"Invalid object name 'dags_audit'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2024-08-31T17:55:39.663+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-31T17:55:39.667+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T17:55:39.710+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=execution_time, run_id=manual__2024-08-31T16:50:00.890695+00:00, execution_date=20240831T165000, start_date=20240831T175539, end_date=20240831T175539
[2024-08-31T17:55:39.832+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-31T17:55:39.905+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T17:55:39.911+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
