[2024-08-31T17:42:38.090+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T17:42:38.427+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.execution_time manual__2024-08-31T16:50:00.890695+00:00 [queued]>
[2024-08-31T17:42:38.446+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.execution_time manual__2024-08-31T16:50:00.890695+00:00 [queued]>
[2024-08-31T17:42:38.450+0000] {taskinstance.py:2306} INFO - Starting attempt 11 of 12
[2024-08-31T17:42:38.482+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): execution_time> on 2024-08-31 16:50:00.890695+00:00
[2024-08-31T17:42:38.493+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3159) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T17:42:38.496+0000] {standard_task_runner.py:64} INFO - Started process 3161 to run task
[2024-08-31T17:42:38.496+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'execution_time', 'manual__2024-08-31T16:50:00.890695+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/envioemail.py', '--cfg-path', '/tmp/tmpfhryz6wt']
[2024-08-31T17:42:38.501+0000] {standard_task_runner.py:91} INFO - Job 341: Subtask execution_time
[2024-08-31T17:42:38.606+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.execution_time manual__2024-08-31T16:50:00.890695+00:00 [running]> on host 19bb8daff211
[2024-08-31T17:42:38.848+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='jorgepons90@gmail.com,facturasjorgepons@gmail.com' AIRFLOW_CTX_DAG_OWNER='Jorge Pons' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='execution_time' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T16:50:00.890695+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T16:50:00.890695+00:00'
[2024-08-31T17:42:38.852+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T17:42:38.898+0000] {logging_mixin.py:188} INFO - start time************2024-08-31 17:42:38.428310+00:00
[2024-08-31T17:42:38.899+0000] {logging_mixin.py:188} INFO - end time************2024-08-31 17:42:38.890792
[2024-08-31T17:42:38.900+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T17:42:38.902+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/funciones.py", line 220, in insertar_tiempo_ejecucion
    duration = (end_date - start_date)
                ~~~~~~~~~^~~~~~~~~~~~
  File "timestamps.pyx", line 526, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
[2024-08-31T17:42:38.936+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_dag, task_id=execution_time, run_id=manual__2024-08-31T16:50:00.890695+00:00, execution_date=20240831T165000, start_date=20240831T174238, end_date=20240831T174238
[2024-08-31T17:42:38.972+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 341 for task execution_time (Cannot subtract tz-naive and tz-aware datetime-like objects.; 3161)
[2024-08-31T17:42:38.994+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T17:42:39.047+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T17:42:39.052+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
