[2024-09-01T11:06:32.319+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-01T11:06:32.637+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.branch_task_dd manual__2024-09-01T11:06:18.679975+00:00 [queued]>
[2024-09-01T11:06:32.657+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.branch_task_dd manual__2024-09-01T11:06:18.679975+00:00 [queued]>
[2024-09-01T11:06:32.661+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-01T11:06:32.693+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_task_dd> on 2024-09-01 11:06:18.679975+00:00
[2024-09-01T11:06:32.705+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=6632) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T11:06:32.708+0000] {standard_task_runner.py:64} INFO - Started process 6634 to run task
[2024-09-01T11:06:32.709+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'branch_task_dd', 'manual__2024-09-01T11:06:18.679975+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpneznjvwc']
[2024-09-01T11:06:32.714+0000] {standard_task_runner.py:91} INFO - Job 392: Subtask branch_task_dd
[2024-09-01T11:06:32.804+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.branch_task_dd manual__2024-09-01T11:06:18.679975+00:00 [running]> on host 19bb8daff211
[2024-09-01T11:06:32.991+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='branch_task_dd' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T11:06:18.679975+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T11:06:18.679975+00:00'
[2024-09-01T11:06:32.994+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-01T11:06:33.021+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-09-01T11:06:33.041+0000] {python.py:237} INFO - Done. Returned value was: send_failure_email
[2024-09-01T11:06:33.042+0000] {branch.py:36} INFO - Branch into send_failure_email
[2024-09-01T11:06:33.043+0000] {skipmixin.py:178} INFO - Following branch send_failure_email
[2024-09-01T11:06:33.078+0000] {skipmixin.py:246} INFO - Skipping tasks [('send_email', -1)]
[2024-09-01T11:06:33.144+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-01T11:06:33.195+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=branch_task_dd, run_id=manual__2024-09-01T11:06:18.679975+00:00, execution_date=20240901T110618, start_date=20240901T110632, end_date=20240901T110633
[2024-09-01T11:06:33.246+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-01T11:06:33.322+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-01T11:06:33.329+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
